simoneb/axios-hooks

src/index.js
Always make sure we're initially starting a hook as loading. This is to prevent bugs from occuring where we check for:
```
if loading return ...
if error return ...
```
return data
=> Change initial state to loading.

src/index.js, src/index.test.js
This is a fix for the issue ["error is not reset if subsequent request succeeds"](https://github.com/simoneb/axios-hooks/issues/8).
Pretty sure this is the correct fix but please review!
=> Reset error when request succeeds

package.json
I think this is the required step to make sure the typescript declaration is included in the built tarball.
If that's not right, then feel free to close.
=> Add index.d.ts to files array in package.json

index.d.ts
I noticed that the TypeScript definitions were incorrect for the useAxios function.
I've updated them in this PR so that a user can use manual mode. I commented about this issue [here](https://github.com/simoneb/axios-hooks/issues/5)
=> Add missing typing parameter

__mocks__/axios.js, index.d.ts, package-lock.json, package.json, src/index.js, src/index.test.js
=> feat: Allow using the cache when triggering requests manually

index.d.ts
Hi,
I really find this package usefull but just needs it to be a bit more strongly typed :-) ! 
This PR should allow typescript users to provide the Response type when using useAxios in the following manner:
`const [{data, loading, error}, execute] = useAxios<ResponseType>(...)` 
This should also be fully backward compatible since it still defaults to any :-)  !
=> Change ResponseValues to a generic

README.md
The reference in the markdown to the **useAxios** section is **useaxiosurlconfig**, but it should be **useaxiosurlconfig-options**
=> Fixed useAxios url

README.md, index.d.ts, src/index.js, src/index.test.js
Builds on top of #34 and includes tests and a refactored implementation which reduces duplication
=> useCache option with tests

index.d.ts, src/index.js
Fixes #33 
I tried but I couldn't manage to write a working test for it.
Something like spying on `lru-cache` `get` would be nice, but I'm not sure how to spy on it, since it's instantiated in `index.js` with `new LRU()`.
=> Add useCache option for standard useAxios call

index.d.ts
When invoking `refetch` method manually, it still returns the `AxiosPromise`, however it has no type defined.
Since we may set this generic type manually, it should use it as well with returned promise.
=> Return AxiosPromise of generic type

src/index.d.ts
Exports the `useAxios` related interfaces so that they can be reused.
For example when creating new hooks building upon `useAxios` it's very
useful/necessary to be able to use/extend/adjust these interfaces.
=> feat(src/index.d.ts): export useAxios related interfaces

README.md
Fix a typo in the docs regarding server side rendering. 
Love this package btw.
=> docs: fix typo in server side rendering

.versionrc.json, src/index.js, test/index.test.js
Fixes #250 by using useLayoutEffect instead of useEffect
=> fix(250): allow using refetch in children components

src/index.d.ts, src/index.js, test/index.test.jsx
Per #376. 
Adds the `cancelOutstandingRequest` to the hook return to allow for manual cancellation of a request.
=> Return cancel outstanding request

src/index.d.ts
When wrapping `useAxios`, it is a little hard to write return type of wrapper hook.
```typescript
import type { AxiosRequestConfig, AxiosPromise } from 'axios';
import useAxios, { ResponseValues, RefetchOptions } from 'axios-hooks';
type MyAPIResponse = { ok: boolean };
function useMyAPI(): [
ResponseValues<MyAPIResponse, any>,
(
config?: AxiosRequestConfig,
options?: RefetchOptions
) => AxiosPromise<MyAPIResponse>,
() => void
] {
return useAxios<MyAPIResponse>({ url: 'https://api.example.com/' });
}
```
I think It is convenient if we can write as following:
```typescript
import useAxios, { UseAxiosResult } from 'axios-hooks';
type MyAPIResponse = { ok: boolean };
function useMyAPI(): UseAxiosResult<MyAPIResponse> {
return useAxios<MyAPIResponse>({ url: 'https://api.example.com/' });
} …
```
=> feat(typings): expose return type of useAxios

src/index.js, test/index.test.jsx
Here's a proposal for #372 
1. Resets the loading property (and keeps previous state) when a outstanding call is cancelled via the manualCancel method. 
- This required tracking how the `cancelOutstandingRequest` is called with the `isCancelledManually` ref. The state update only occurs when the `cancelManually` method is executed.
2. Resets the loading property when a manual call is cancelled via a config change to the hook (on new line 375). 
- Required checking that the component is mounted as it attempts to update the state on a config change (that is also triggered on an unmount). This was done with the `isMounted` ref and the empty dependency useEffect.
*Note:* Point 2 is done under the assumption that changes in the config and option should cancel a outstanding request when the …
=> feature(manual cancellation update): Reset loading state when outstanding call is cancelled

src/index.d.ts
I have no issue to reference, figured a PR would suffice; happy to make one if desired.
Happy there's definitions included, but I noticed in implementing this, the type returned by error in `const [{ error }] = useAxios('…')` was coming back as an `AxiosError | undefined`, but in the code ([at L137](https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L137) + [at L148](https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L148)) it is set to `null` and never `undefined`.
**My investigation:**
1. It looks like this is always provided, never `undefined`.
2. It looks like this is either defined as `null` ([L137](https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L137), [L148](https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L148)) or via a …
=> Typescript: Fix `ResponseValues['error']` to match the null value returned.

package-lock.json, package.json, src/index.d.ts
Closes https://github.com/simoneb/axios-hooks/issues/610
BREAKING CHANGE: requires axios@^0.24.0
=> feat: apply type-safe for AxiosRequestConfig data parameter

package.json
I noticed that the package requires React ^16.8.0-0 or ^17.0.0 as a peer dependency, but ^18.0.0 is not accepted. This causes problems with npm 7+ as peer dependency conflicts completely block dependency installations.
=> Support react 18 as peer dependency

src/index.js, test/index.test.jsx
this code change fixes issue described in #609 
fixes #609
=> fix: autoCancel respected when hook is unmounted

README.md
=> Add section to cover response contamination in tests due to caching

README.md
Fixes a typo in the README.md file
- Corrected the typo from `reects` to `rejects`
The original sentence read:
> Returns
> 
> A promise containing the response. If the request is unsuccessful, the promise **reects** and the rejection must be handled manually.
The corrected sentence now reads:
> **Returns**
>
>  A promise containing the response. If the request is unsuccessful, the promise **rejects** and the rejection must be handled manually.
This change improves the clarity and correctness of the documentation by fixing a typographical error.
I would also like to take this opportunity to express my gratitude for the well-elaborated documentation and the exceptional support provided by the library. The clarity of explanations and the collaborative community have greatly contributed to my …
=> docs: correct a typo in README.md
